### ISSUE TITLE
Assertion failed: (err == 0), function update_tcp_mss, file main.c, line 198.

### ISSUE THREAD

**Issue by fbion** [cachefiles/notbevpn#2]
$ sudo ./toyclient -s ./ifup-utun0.sh -t utun5 -p udp -i 10.3.0.15 10.3.0.1:1082
Password:
uid = 0
setuids = 0
run sh uid = 0
setup_cmd = ./ifup-utun0.sh utun5 10.3.0.1
add net default: gateway 10.3.0.15
udpfd = 4
udp bind err = -1
Assertion failed: (err == 0), function update_tcp_mss, file main.c, line 198.
Abort trap: 6
这是怎么回事

**Comment by pagxir** [comment]
UDP 这个是没法用的，因为没有server端。对于UDP，只需要执行:
 toyclient -s ./ifup-tun0.sh -t tun0 -p udp cc.yrli.bid:139

不需要加 -i 参数，-i 是用来指定出口的本地端IP的。
