### ISSUE TITLE
怎么解决Resource busy问题？

### ISSUE THREAD

**Issue by luckypoem** [cachefiles/notbevpn#3]
on my mac.
yudeMacBook-Air:notbevpn brite$ sudo ./toyclient -s ./ifup-utun0.sh -t utun0 -p tcp -i 10.3.0.15 10.3.0.1:8000
connect[AF_SYS_CONTROL]vpn_tun_alloc: : Resource busy
yudeMacBook-Air:notbevpn brite$

谢谢

**Comment by pagxir** [comment]
不要使用 utun0 应该用utun1。你用tcp模式是为了使用tun2socks的功能么？

在 2019年7月16日星期二，luckypoem <notifications@github.com> 写道：

**Comment by luckypoem** [comment]
@pagxir 
昨晚终于搞好，可翻墙了。可今天早上起来，运行：
sudo ./toyclient -s ./ifup-utun1-new.sh -t utun1 -p tcp -i 10.3.0.15 10.3.0.1:8000
显示：
add net default: gateway 10.3.0.15
ip route add default dev utun1
route: writing to routing socket: File exists
add net default: gateway utun1: File exists

无法翻墙成功。
运行什么命令来消除“File exists”的提示呢？

**Comment by luckypoem** [comment]
建议再写个解除路由设置的脚本，这样用起来才更方便

**Comment by luckypoem** [comment]
哦，运行：
sudo route -n delete -net default

sudo echo ip route delete default dev ${tun_dev}
即可。

**Comment by briteming** [comment]
hi.

一定要搭配shadowsocks-libev 的客户端使用才行吗？不能搭配其它的local socks5 proxy使用吗？因为在我这里，shadowsocks-libev 的客户端已经无法用来翻墙。
但是搭配其它的local socks5 proxy使用，运行：
sudo ./toyclient -s ./ifup-utun10-new.sh -t utun10 -p tcp -i 10.3.0.15 10.3.0.1:1082
却出现Dnat failure的提示，不知为什么？
这里，1082是我的local socks5 proxy监听的端口

**Comment by pagxir** [comment]
不一定要使用libev的，ssh -D 出来的socks一样OK的。至于dnat failure 不一定是失败的，你可以先测试确认失败再分析原因。

briteming ***@***.***> 于 2022年2月13日周日 下午12:00写道：

**Comment by briteming** [comment]
hi.

yudeMacBook-Air:notbevpn ym$ sudo ./toyclient -s ./ifup-utun10-new.sh -t utun10 -p tcp -i 10.3.0.15 10.3.0.1:7058
Password:
add net default: gateway 10.3.0.15
ip route add default dev utun10
route: writing to routing socket: File exists
add net default: gateway utun10: File exists

 2-21 14:16:32.044 D nat failure
 2-21 14:16:33.045 D nat failure
 2-21 14:16:34.045 D nat failure
 2-21 14:16:35.046 D nat failure

还是不行。我觉得是ssh tunnel client无法绑定10.3.0.1地址造成的失败。我试了一下，好像只有shadowsocks-libev client可以 绑定10.3.0.1这样的地址，其它的local socks5 proxy只能绑定／监听0.0.0.0或127.0.0.1，无法绑定10.3.0.1这样的地址。我的理解对吗

**Comment by pagxir** [comment]
把verboselog打开看看报文转换跑到那个地方了。
export LOGABLE_TAGS=FEWIDV 

感觉应该是路由没配置对，导致转换后的报文又路由回来了。可以配一下策略路由，或者不要直接将default加进去走utun。你可以试试抓包utun接口，看看报文是怎么样的

**Comment by pagxir** [comment]
有另外一个类似的项目，kone你可以试试

**Comment by briteming** [comment]
怎么配置策略路由？

**Comment by briteming** [comment]
yudeMacBook-Air:notbevpn ym$ cat ifup-utun10-new.sh
#!/bin/bash
tun_dev=utun10
ifconfig ${tun_dev} 10.3.0.1/24 10.3.0.15 up
route -n add -net default -ifscope ${tun_dev} 10.3.0.15
echo ip route add default dev ${tun_dev}
route add -net default -interface ${tun_dev}
yudeMacBook-Air:notbevpn ym$

没有看懂ifup-utun10-new.sh的内容。

我只熟悉这样设置路由：
sudo route delete default
sudo route add default 11.9.0.1
sudo route add vps-public-ip 192.168.1.1

 11.9.0.1是vps internal ip,192.168.1.1是我的无线路由器的ip.

你的那个sh文件如果要写成类似上面的路由命令，该怎么写？

**Comment by briteming** [comment]
hi.

你说用ssh -D, 好像不行：
yudeMacBook-Air:notbevpn ym$ ssh -D 10.3.0.1:7058 root@my-vps-public-ip -p 27348
root@my-vps-public-ip's password: 
bind: Can't assign requested address
channel_setup_fwd_listener_tcpip: cannot listen to port: 7058
Could not request local forwarding.
root@racknerd-7b97d8:~#

那么只能搭配ss-libev使用？？

**Comment by pagxir** [comment]
macos的策略路由需要用ipfw配规则

**Comment by briteming** [comment]
我觉得根本原因还是‘只有shadowsocks-libev client可以 绑定10.3.0.1这样的地址，其它的local socks5 proxy，比如ssh -D只能监听0.0.0.0或127.0.0.1，无法监听10.3.0.1这样的地址‘，你确认你试过用ssh -D搭配你这个全局代理程序成功翻墙吗？你亲自试过吗

**Comment by pagxir** [comment]
你大概率不是学计算机/网络的，你还是找身边的计算机专业的帮忙或者放弃，或者选其他的。

**Comment by briteming** [comment]
我试过很多其它的全局代理程序，都很ok.你这个程序有点另类。

我也正这样想，还是谢谢你。
