### ISSUE TITLE
nat failure

### ISSUE THREAD

**Issue by weibo3721** [cachefiles/notbevpn#4]
连接后总是出现
 2-05 14:43:13.696 D nat failure
 2-05 14:43:14.020 D nat failure
 2-05 14:43:15.025 D nat failure
类似错误,

**Comment by pagxir** [comment]
这并不是错误，是因为一个TCP连接因为完成了4次挥手，跟踪信息已经删除，当再次接收到这条连接的报文就会打印出来的提示。
